name: desafio-jaya-micronaut

on: [push]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up JDK 11

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Running Checkstyle
        run: ./gradlew clean checkstyleMain checkstyleTest

  test:
    runs-on: ubuntu-latest
    needs: [ checkstyle ]
    steps:
      - uses: actions/checkout@v2
        name: Set up JDK 11

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Running Checkstyle
        run: ./gradlew test --no-daemon -x checkstyleTest -x checkstyleMain

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
        name: Set up JDK 11

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle        
        run: ./gradlew clean build --no-daemon -x checkstyleTest -x checkstyleMain -x test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/desafio-jaya-micronaut:latest
      
